# This is a basic workflow to help you get started with Actions

name: Update Packagist

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Ping Packagist
        run: curl -XPOST -H'content-type:application/json' "https://packagist.org/api/update-package?username=shannah&apiToken=${{secrets.PACKAGIST_API_KEY}}" -d'{"repository":{"url":"https://packagist.org/packages/weblite/swete"}}'
      
